image: node:latest

pages:
      stage: deploy
      script:
              - npm config set registry https://registry.npmjs.org
              - npm i
              - npm run lint
              - npm run build
        artifacts:
              path:
                    - dist
        only:
              - master